# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy

class RunnersItem(scrapy.Item):
    racedate = scrapy.Field()
    racecoursename = scrapy.Field()
    racecourseid = scrapy.Field()
    racename = scrapy.Field()
    racetypehorse = scrapy.Field()
    racetypeconditions= scrapy.Field()
    handicapstakes= scrapy.Field()
    racetypehs = scrapy.Field()
    ages = scrapy.Field()
    raceclass = scrapy.Field()
    distance = scrapy.Field()
    going= scrapy.Field()
    runners= scrapy.Field()
    horsename = scrapy.Field()
    trainername = scrapy.Field()
    jockeyname = scrapy.Field()
    FINALPOS = scrapy.Field()
    poscolor= scrapy.Field()
    winsp= scrapy.Field()
    bfsp= scrapy.Field()
    ratingrank = scrapy.Field()
    rating= scrapy.Field()
    placed= scrapy.Field()
    raceno= scrapy.Field()
    #other stats?

class FlatstatsItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    snapshotid= scrapy.Field()
    systemname= scrapy.Field()
    isTurf = scrapy.Field()
    exposure= scrapy.Field()
    query = scrapy.Field()
    red_rows_ct = scrapy.Field()
    blue_rows_ct  = scrapy.Field()
    green_rows_ct = scrapy.Field()
    total_rows_ct = scrapy.Field()
    red_rows_pc= scrapy.Field()
    blue_rows_pc= scrapy.Field()
    green_rows_pc= scrapy.Field()
    redrows= scrapy.Field()
    greenrows = scrapy.Field()
    bluerows = scrapy.Field()
    bfruns= scrapy.Field()
    levelbspprofit= scrapy.Field()
    levelbsprofitpc= scrapy.Field()
    bfwins= scrapy.Field()
    bfwinpc= scrapy.Field()
    expectedwins= scrapy.Field()
    a_e= scrapy.Field()
    archie_allruns= scrapy.Field()
    expected_last50= scrapy.Field()
    archie_last50= scrapy.Field()
    last50wins= scrapy.Field()
    last50pc= scrapy.Field()
    a_e_last50= scrapy.Field()
    profit_last50= scrapy.Field()
    last50str= scrapy.Field()
    last28daysruns= scrapy.Field()
    individualrunners= scrapy.Field()
    uniquewinners= scrapy.Field()
    uniquewinnerstorunnerspc= scrapy.Field()
    longestwinningstreak= scrapy.Field()
    longestlosingstreak= scrapy.Field()
    averagelosingstreak= scrapy.Field()
    yearstats= scrapy.Field()
    yearcolorcounts= scrapy.Field()
    totalbackyears = scrapy.Field()
    runners = scrapy.Field()
